#!/bin/bash

song="$(mpc listall | sort -nfb | dmenu -nb "#222222" -sb "#303030" -fn terminus -y 300 -x 1039 -z 500 -i -l 10)" || exit 0
mpc insert "$song" 
mpc next > /dev/null
notify-send -u low -i none "Playing: $song"
